version: '3'
services:
  mysql:
    build:
      context: "8.0"
      dockerfile: Dockerfile.oracle
    image: ccr.ccs.tencentyun.com/664301573/my-mysql-image
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_buffer_pool_size=1G --join_buffer_size=512M --sort_buffer_size=128M --read_rnd_buffer_size=128M
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: my-secret-pw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
